image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - https://github.com/sjpgarcia/vscode-language-purescript/releases/download/v0.2.7/nwolverson.language-purescript-0.2.7.vsix
    - https://github.com/sjpgarcia/vscode-ide-purescript/releases/download/v0.25.5/nwolverson.ide-purescript-0.25.6.vsix