name: Build and Deploy

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2.3.1

      - name: Install PureScript
        uses: purescript-contrib/setup-purescript@main

      - name: Install Pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest

      - name: Install and Build
        run: |
          pnpm i
          pnpm bundle

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: public